"""SYNTHETIC lab data for the connected-data journey and its tests. Generated from a fixed seed; nothing here is a measurement.

PostgreSQL: specimens (60 rows), assays (63 rows: SP001..SP055 once, SP001..SP005 a second time as replicate assays, 0 for SP056..SP060),
            secret_notes (a table the `reader` role cannot SELECT).
S3: features/spectra.csv (SP001..SP055 plus the stray id SP999), images/<id>.png (55 small synthetic PNG files, sizes vary)."""
from __future__ import annotations

import io

import numpy as np
import pandas as pd

N_SPECIMENS = 60
WITH_FEATURES = 55
LABEL = "SYNTHETIC DATA - generated by python/connectors/synthetic.py with a fixed seed"


def specimens() -> pd.DataFrame:
    rng = np.random.default_rng(20260101)
    ids = [f"SP{i:03d}" for i in range(1, N_SPECIMENS + 1)]
    return pd.DataFrame({"specimen_id": ids, "site": rng.choice(["north", "south", "east"], N_SPECIMENS), "collected": pd.date_range("2025-03-01", periods=N_SPECIMENS, freq="D").date,
                         "ph": np.round(rng.uniform(5.5, 8.5, N_SPECIMENS), 3), "temp_c": np.round(rng.uniform(10, 30, N_SPECIMENS), 2)})


def spectra() -> pd.DataFrame:
    rng = np.random.default_rng(7)
    ids = [f"SP{i:03d}" for i in range(1, WITH_FEATURES + 1)] + ["SP999"]
    a, b = np.round(rng.uniform(0.1, 1.0, len(ids)), 4), np.round(rng.uniform(0.0, 0.6, len(ids)), 4)
    return pd.DataFrame({"specimen_id": ids, "absorbance_a": a, "absorbance_b": b})


def assays() -> pd.DataFrame:
    sp, spec = specimens().set_index("specimen_id"), spectra().set_index("specimen_id")
    rng = np.random.default_rng(99)
    rows = []
    for sid in list(sp.index[:WITH_FEATURES]) + list(sp.index[:5]):  # the first five specimens were assayed twice
        base = 1.5 * sp.loc[sid, "ph"] + 0.4 * sp.loc[sid, "temp_c"] + 6.0 * spec.loc[sid, "absorbance_a"] - 4.0 * spec.loc[sid, "absorbance_b"]
        rows.append({"specimen_id": sid, "response": round(float(base + rng.normal(0, 0.5)), 4)})
    # a few assays for specimens that have no spectra row: SP056, SP057 (ids present in specimens, not in the S3 file)
    for sid in ["SP056", "SP057", "SP058"]:
        rows.append({"specimen_id": sid, "response": round(float(1.5 * sp.loc[sid, "ph"] + 0.4 * sp.loc[sid, "temp_c"] + rng.normal(0, 0.5)), 4)})
    return pd.DataFrame(rows)


def seed_postgres(pg) -> None:
    sp, ay = specimens(), assays()
    with pg.admin() as c:
        c.execute("DROP TABLE IF EXISTS assays; DROP TABLE IF EXISTS specimens; DROP TABLE IF EXISTS secret_notes")
        c.execute("CREATE TABLE specimens (specimen_id text PRIMARY KEY, site text NOT NULL, collected date NOT NULL, ph double precision, temp_c double precision)")
        c.execute("CREATE TABLE assays (assay_id serial PRIMARY KEY, specimen_id text NOT NULL REFERENCES specimens, response double precision)")
        c.execute("CREATE TABLE secret_notes (id int, note text)")
        c.execute("INSERT INTO secret_notes VALUES (1, 'not for the reader role')")
        with c.cursor() as cur:
            cur.executemany("INSERT INTO specimens VALUES (%s,%s,%s,%s,%s)", [tuple(r) for r in sp.itertuples(index=False, name=None)])
            cur.executemany("INSERT INTO assays (specimen_id, response) VALUES (%s,%s)", [tuple(r) for r in ay.itertuples(index=False, name=None)])
        c.execute("DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='reader') THEN CREATE ROLE reader LOGIN; END IF; END $$")
        c.execute("GRANT USAGE ON SCHEMA public TO reader")
        c.execute("GRANT SELECT ON specimens, assays TO reader")
        c.execute("REVOKE ALL ON secret_notes FROM reader")
        c.execute("ANALYZE")


def png_bytes(i: int) -> bytes:
    from PIL import Image

    rng = np.random.default_rng(i)
    n = 8 + (i % 7) * 4
    arr = rng.integers(0, 255, (n, n, 3), dtype=np.uint8)
    buf = io.BytesIO()
    Image.fromarray(arr).save(buf, format="PNG")
    return buf.getvalue()


def seed_s3(s3, bucket: str, versioned: bool = True) -> None:
    c = s3.client()
    c.create_bucket(Bucket=bucket)
    if versioned:
        c.put_bucket_versioning(Bucket=bucket, VersioningConfiguration={"Status": "Enabled"})
    c.put_object(Bucket=bucket, Key="features/spectra.csv", Body=spectra().to_csv(index=False).encode(), ContentType="text/csv")
    for i in range(1, WITH_FEATURES + 1):
        c.put_object(Bucket=bucket, Key=f"images/SP{i:03d}.png", Body=png_bytes(i), ContentType="image/png")
