// Real owned Chrome, real saved drafts and API validation. No invented graph evidence.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {default:puppeteer}=await import(pathToFileURL(process.env.VOID_SMOKE_PUPPETEER).href);
const output=process.env.VOID_SMOKE_OUTPUT;
const evidence={status:'failed',fixture:'SYNTHETIC native agent outline',runtimeErrors:[],apiErrors:[],consoleWarnings:[]};
const browser=await puppeteer.launch({executablePath:process.env.VOID_SMOKE_CHROME,headless:true,
  args:process.platform==='linux'?['--no-sandbox']:[],defaultViewport:{width:1600,height:1100}});
process.once('SIGTERM',()=>void browser.close());process.once('SIGINT',()=>void browser.close());
const page=await browser.newPage();page.setDefaultTimeout(45000);
page.on('pageerror',e=>evidence.runtimeErrors.push(e.message));
page.on('dialog',d=>d.accept());
page.on('console',m=>{if(['warn','warning','error'].includes(m.type()))evidence.consoleWarnings.push({type:m.type(),text:m.text()});});
page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/')&&r.status()>=400)evidence.apiErrors.push({status:r.status(),url:r.url()});});
const fill=async(selector,value)=>{
  const el=await page.waitForSelector(selector);
  await el.evaluate((el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
  await el.press('Tab');
};
const click=async(label)=>{
  await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(b=>b.textContent.trim()===t&&!b.disabled),{},label);
  for(const h of await page.$$('button'))if(await h.evaluate((e,t)=>e.textContent.trim()===t&&!e.disabled,label))return h.click();
};
const disabled=selector=>page.$eval(selector,e=>e.disabled);
const save=async()=>{
  const pending=page.waitForResponse(r=>r.request().method()==='PUT'&&new URL(r.url()).pathname==='/api/projects/SYNTHETIC_agent_outline');
  for(const h of await page.$$('.topbar button'))if(await h.evaluate(e=>e.textContent.startsWith('Save'))){await h.click();break;}
  const response=await pending;assert.equal(response.status(),200);
  return page.evaluate(async()=>{const r=await fetch('/api/projects/SYNTHETIC_agent_outline');if(!r.ok)throw Error('Read saved draft '+r.status);return r.json();});
};
const shortcut=async(redo=false)=>{
  await page.evaluate(()=>document.activeElement?.blur());
  await page.keyboard.down(process.platform==='darwin'?'Meta':'Control');
  if(redo)await page.keyboard.down('Shift');
  await page.keyboard.press('z');
  if(redo)await page.keyboard.up('Shift');
  await page.keyboard.up(process.platform==='darwin'?'Meta':'Control');
};
const native=graph=>page.evaluate(async graph=>(await fetch('/api/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph})})).json(),graph);
const load=async data=>{await page.evaluate(async data=>{const r=await fetch('/api/projects/SYNTHETIC_agent_outline',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error('Stored agent fixture '+r.status);},data);await page.waitForSelector('select[aria-label="open project"] option[value="project:SYNTHETIC_agent_outline"]');await page.select('select[aria-label="open project"]','project:SYNTHETIC_agent_outline');await page.waitForFunction(()=>document.querySelector('.toast[role="status"]')?.textContent.includes("Loaded project 'SYNTHETIC_agent_outline'"));await page.waitForSelector('.agent-outline');};
const openOutline=async()=>{if(!(await page.$eval('.agent-outline',e=>e.open)))await page.click('.agent-outline summary');};
const ready=async hash=>{await openOutline();await page.waitForFunction(hash=>document.querySelector('.agent-outline .provenance')?.textContent.includes(hash),{},hash);};
const ids=()=>page.$$eval('.agent-outline tbody tr',rows=>rows.map(r=>r.querySelector('button[aria-label^="inspect agent outline "]').getAttribute('aria-label').slice('inspect agent outline '.length)));
const inspect=async id=>{const b=await page.waitForSelector(`[aria-label="inspect agent outline ${id}"]`);await b.focus();await b.press('Enter');await page.waitForFunction(id=>document.querySelector('input[aria-label="node id"]')?.value===id,{},id);};
try{
 await page.goto(process.env.VOID_SMOKE_URL);await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='reference_cnn'&&document.querySelectorAll('.react-flow__node').length===10);await page.waitForSelector('select[aria-label="open project"] option[value="example:serving_state"]');await page.select('select[aria-label="open project"]','example:serving_state');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='serving_state');await fill('input[aria-label="project id"]','SYNTHETIC_agent_outline');const initial=await save();
 const graph={...initial.graph,edges:initial.graph.edges.filter(e=>e.from.node!=='tick'),agent:{...initial.graph.agent,routes:[{id:'declared_route',from:'tick',cases:[{id:'positive',label:'SYNTHETIC declared route only',when:{field:'n',op:'>',value:0},to:'answer'}],default:'END'}],joins:[]}};const source={graph,ui:{...initial.ui,description:'SYNTHETIC declared native state/control contracts; no execution/model-quality claim',synthetic:true,unknown:{preserved:true}}};await load(source);const baseline=await save();assert.deepEqual(baseline.graph,source.graph);assert.deepEqual(baseline.ui,source.ui);const report=await native(baseline.graph);evidence.seedNative=report;assert(report.ok);await ready(report.graphHash);evidence.baseline={saved:baseline,native:report};
 evidence.stage='actual native reads/writes/effects, declared control route search and keyboard inspector';assert.deepEqual(await ids(),['tick','answer']);for(const id of await ids()){const row=await page.$eval(`[aria-label="inspect agent outline ${id}"]`,b=>b.closest('tr').textContent);for(const value of [...report.nodes[id].reads,...report.nodes[id].writes,...report.nodes[id].effects])assert(row.includes(value));}await fill('input[aria-label="agent outline search"]','SYNTHETIC declared route');assert.deepEqual(await ids(),['tick']);await inspect('tick');await fill('input[aria-label="agent outline search"]','');const after=await save();assert.deepEqual(after.graph,baseline.graph);assert.deepEqual(after.ui,baseline.ui);assert(await disabled('button[aria-label="undo draft edit"]'));await page.screenshot({path:path.join(output,'native-agent-outline.png'),fullPage:true,captureBeyondViewport:false});
 evidence.stage='actual native error filter does not hide unimplemented fields';const invalidGraph={...graph,nodes:graph.nodes.map(n=>n.id==='tick'?{...n,config:{...n.config,assignments:[{field:'missing_field',kind:'increment',by:1}]}}:n)};await load({graph:invalidGraph,ui:baseline.ui});const invalid=await save(),invalidReport=await native(invalid.graph);assert(!invalidReport.ok);await ready(invalidReport.graphHash);await page.click('input[aria-label="agent outline native errors only"]');const expectedIds=[...new Set(invalidReport.diagnostics.filter(d=>d.severity==='error'&&invalid.graph.nodes.some(n=>n.id===d.nodeId)).map(d=>d.nodeId))];assert.deepEqual(await ids(),expectedIds);assert(expectedIds.includes('tick'));const codes=invalidReport.diagnostics.filter(d=>d.severity==='error'&&d.nodeId==='tick').map(d=>d.code),content=await page.$eval('.agent-outline tbody',e=>e.textContent);assert(codes.every(c=>content.includes(c)));await inspect('tick');assert.deepEqual((await save()).graph,invalid.graph);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.invalid={saved:invalid,native:invalidReport};await page.click('input[aria-label="agent outline native errors only"]');
 evidence.stage='valid native constructor identity and real pending report suppression';const rename=id=>id==='tick'?'constructor':id;const constructorGraph={...graph,nodes:graph.nodes.map(n=>({...n,id:rename(n.id)})),edges:graph.edges.map(e=>({...e,from:{...e.from,node:rename(e.from.node)},to:{...e.to,node:rename(e.to.node)}})),agent:{...graph.agent,routes:graph.agent.routes.map(r=>({...r,from:rename(r.from)}))}};
 let reached;const seen=new Promise(resolve=>{reached=resolve;}),held=[];await page.setRequestInterception(true);const gate=request=>{const data=request.postData();if(new URL(request.url()).pathname==='/api/validate'&&request.method()==='POST'&&data&&JSON.parse(data).graph.nodes.some(n=>n.id==='constructor')){held.push(request);reached();}else void request.continue();};page.on('request',gate);await load({graph:constructorGraph,ui:{...baseline.ui,positions:{}}});await seen;await openOutline();await page.waitForFunction(()=>document.querySelector('.agent-outline .provenance')?.textContent.includes('Native agent validation pending'));assert.equal((await page.$$eval('.agent-outline tbody tr',rows=>rows.filter(r=>r.textContent.includes('Native node analysis unavailable.')).length)),2);assert.equal((await page.$eval('.agent-outline',e=>e.textContent)).includes('missing_field'),false);evidence.pending={realRequestsHeld:held.length,visible:await page.$eval('.agent-outline .provenance',e=>e.textContent)};for(const request of held)await request.continue();page.off('request',gate);await page.setRequestInterception(false);
 const constructor=await save(),constructorReport=await native(constructor.graph);assert(constructorReport.ok);await ready(constructorReport.graphHash);assert.deepEqual(await ids(),['constructor','answer']);await inspect('constructor');assert.deepEqual((await save()).ui,constructor.ui);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.constructor={saved:constructor,native:constructorReport};
 evidence.stage='75 real native nodes,50+25 pages,back/search reset and no layout/history edit';const count=75,nodes=Array.from({length:count},(_,i)=>({id:'node_'+String(i).padStart(3,'0'),type:'agent.set_state',version:'1.0.0',config:{assignments:[{field:'n',kind:'increment',by:1}]}})),edges=Array.from({length:count+1},(_,i)=>({id:'edge_'+i,kind:'control',from:{node:i===0?'START':nodes[i-1].id,port:'out'},to:{node:i===count?'END':nodes[i].id,port:'in'}}));const pagesGraph={...graph,nodes,edges,agent:{...graph.agent,routes:[],joins:[],limits:{maxSteps:100}}};await load({graph:pagesGraph,ui:{schemaVersion:'1.0.0',positions:{},synthetic:true,description:'SYNTHETIC75native nodes for pagination; no run/model-quality/performance claim'}});const pages=await save(),pagesReport=await native(pages.graph);assert(pagesReport.ok);await ready(pagesReport.graphHash);const first=await ids();assert.equal(first.length,50);assert.equal(first[0],'node_000');await click('Next agent outline nodes');const second=await ids();assert.equal(second.length,25);assert.equal(second[0],'node_050');await click('Previous agent outline nodes');assert.deepEqual(await ids(),first);await click('Next agent outline nodes');await fill('input[aria-label="agent outline search"]','node_074');assert.deepEqual(await ids(),['node_073','node_074']);assert(await page.$$eval('.agent-outline button',bs=>bs.find(b=>b.textContent==='Previous agent outline nodes').disabled));await inspect('node_074');assert.deepEqual((await save()).graph,pages.graph);assert.deepEqual((await save()).ui,pages.ui);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.pages={saved:pages,native:pagesReport,first,second};
 assert.deepEqual(evidence.runtimeErrors,[]);assert.deepEqual(evidence.apiErrors,[]);assert.deepEqual(evidence.consoleWarnings,[]);evidence.browserVersion=await browser.version();evidence.status='passed';console.log('PASS native agent outline → exact state/effect/control references → keyboard inspection/no edits → native errors/pending guard → constructor ID →75node paging');
}catch(error){evidence.error=String(error);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true,captureBeyondViewport:false}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync(path.join(output,'evidence.json'),JSON.stringify(evidence,null,2));await browser.close();}
