// Real owned Chrome, real saved drafts and API validation. No invented graph evidence.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {default:puppeteer}=await import(pathToFileURL(process.env.VOID_SMOKE_PUPPETEER).href);
const output=process.env.VOID_SMOKE_OUTPUT;
const evidence={status:'failed',fixture:'SYNTHETIC native graph command menu',runtimeErrors:[],apiErrors:[],consoleWarnings:[]};
const browser=await puppeteer.launch({executablePath:process.env.VOID_SMOKE_CHROME,headless:true,
  args:process.platform==='linux'?['--no-sandbox']:[],defaultViewport:{width:1600,height:1100}});
process.once('SIGTERM',()=>void browser.close());process.once('SIGINT',()=>void browser.close());
const page=await browser.newPage();page.setDefaultTimeout(45000);
page.on('pageerror',e=>evidence.runtimeErrors.push(e.message));
page.on('dialog',d=>d.accept());
page.on('console',m=>{if(['warn','warning','error'].includes(m.type()))evidence.consoleWarnings.push({type:m.type(),text:m.text()});});
page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/')&&r.status()>=400)evidence.apiErrors.push({status:r.status(),url:r.url()});});
const fill=async(selector,value)=>{
  const el=await page.waitForSelector(selector);
  await el.evaluate((el,v)=>{Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
  await el.press('Tab');
};
const click=async(label)=>{
  await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(b=>b.textContent.trim()===t&&!b.disabled),{},label);
  for(const h of await page.$$('button'))if(await h.evaluate((e,t)=>e.textContent.trim()===t&&!e.disabled,label))return h.click();
};
const disabled=selector=>page.$eval(selector,e=>e.disabled);
const save=async()=>{
  const pending=page.waitForResponse(r=>r.request().method()==='PUT'&&new URL(r.url()).pathname==='/api/projects/SYNTHETIC_commands');
  for(const h of await page.$$('.topbar button'))if(await h.evaluate(e=>e.textContent.startsWith('Save'))){await h.click();break;}
  const response=await pending;assert.equal(response.status(),200);
  return page.evaluate(async()=>{const r=await fetch('/api/projects/SYNTHETIC_commands');if(!r.ok)throw Error('Read saved draft '+r.status);return r.json();});
};
const shortcut=async(redo=false)=>{
  await page.evaluate(()=>document.activeElement?.blur());
  await page.keyboard.down(process.platform==='darwin'?'Meta':'Control');
  if(redo)await page.keyboard.down('Shift');
  await page.keyboard.press('z');
  if(redo)await page.keyboard.up('Shift');
  await page.keyboard.up(process.platform==='darwin'?'Meta':'Control');
};

const open=async()=>{await page.evaluate(()=>document.activeElement?.blur());await page.keyboard.down(process.platform==='darwin'?'Meta':'Control');await page.keyboard.press('k');await page.keyboard.up(process.platform==='darwin'?'Meta':'Control');await page.waitForFunction(()=>document.querySelector('.command-menu')?.open&&document.activeElement?.getAttribute('aria-label')==='find graph commands');};
const search=async query=>{await fill('input[aria-label="find graph commands"]',query);await page.focus('input[aria-label="find graph commands"]');await page.waitForFunction(q=>[...document.querySelectorAll('.command-results button')].every(b=>b.textContent.toLowerCase().includes(q.toLowerCase())),{},query);};
const execute=async query=>{await open();await search(query);await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.querySelector('.command-menu').open);};
const validate=graph=>page.evaluate(async graph=>{const r=await fetch('/api/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph})});if(!r.ok)throw Error('Native validation '+r.status);return r.json();},graph);
const unchanged=(before,after)=>{assert.deepEqual(after.graph,before.graph);assert.deepEqual(after.ui,before.ui);assert.equal(after.graphHash,before.graphHash);};
try{
 await page.goto(process.env.VOID_SMOKE_URL);await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='reference_cnn'&&document.querySelectorAll('.react-flow__node').length===10);
 await fill('input[aria-label="project id"]','SYNTHETIC_commands');const baseline=await save();evidence.baseline=baseline;
 evidence.stage='literal search, native dialog focus and paging';await open();const dialogGeometry=await page.evaluate(()=>{const dialog=document.querySelector('.command-menu'),title=dialog.querySelector('h2').getBoundingClientRect(),close=dialog.querySelector('[aria-label="close graph commands"]').getBoundingClientRect();return {titleRight:title.right,closeLeft:close.left,scrollWidth:dialog.scrollWidth,clientWidth:dialog.clientWidth};});assert(dialogGeometry.titleRight<=dialogGeometry.closeLeft);assert(dialogGeometry.scrollWidth<=dialogGeometry.clientWidth);evidence.dialogGeometry=dialogGeometry;assert.equal(await page.$$eval('.command-results button',bs=>bs.length),25);await click('Next commands');assert((await page.$eval('.command-menu [role="status"]',e=>e.textContent)).includes('page 2'));await click('Previous commands');
 for(let i=0;i<4;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.querySelector('.command-menu').contains(document.activeElement)));}
 await search('.*');assert.equal(await page.$$eval('.command-results button',bs=>bs.length),0);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.command-menu').open);unchanged(baseline,await save());
 evidence.stage='inspect actual node via Enter, unchanged native graph';await execute('Inspect conv_1');await page.waitForFunction(()=>document.querySelector('input[aria-label="node id"]').value==='conv_1');unchanged(baseline,await save());
 evidence.stage='text editor shortcut is left to input';await page.focus('input[aria-label="node id"]');await page.keyboard.down(process.platform==='darwin'?'Meta':'Control');await page.keyboard.press('k');await page.keyboard.up(process.platform==='darwin'?'Meta':'Control');assert(!(await page.$eval('.command-menu',e=>e.open)));await page.evaluate(()=>document.activeElement?.blur());
 evidence.stage='real existing workspace navigation';await execute('Open Records');await page.waitForFunction(()=>[...document.querySelectorAll('[aria-label="workspace"] [role="tab"]')].some(b=>b.textContent==='Records'&&b.getAttribute('aria-selected')==='true'));unchanged(baseline,await save());await execute('Open Graph');await page.waitForSelector('.react-flow');
 evidence.stage='disabled history command refuses edit';await open();await search('Undo draft edit');assert(await page.$eval('[aria-label="run command undo"]',b=>b.disabled));await page.keyboard.press('Enter');assert(await page.$eval('.command-menu',e=>e.open));await page.keyboard.press('Escape');unchanged(baseline,await save());
 evidence.stage='disconnected creation with registered native defaults, no anchor autowire';await execute('Inspect conv_1');await execute('diag.probe@');const created=await save();evidence.createdSaved=created;const node=created.graph.nodes.find(n=>n.id==='probe_1');assert(node);assert.equal(node.type,'diag.probe');const registry=await page.evaluate(async()=>(await fetch('/api/registry')).json());assert.deepEqual(node.config,registry.ops.find(o=>o.type==='diag.probe').defaults);assert.deepEqual(created.graph.edges,baseline.graph.edges);assert.deepEqual(created.graph.nodes.filter(n=>n.id!=='probe_1'),baseline.graph.nodes);const missing=await validate(created.graph);assert(!missing.ok);assert(missing.diagnostics.some(d=>d.code==='E_MISSING_INPUT'&&d.nodeId==='probe_1'));await page.waitForFunction(()=>document.querySelector('.node-inspector')?.textContent.includes('E_MISSING_INPUT'));evidence.created={saved:created,native:missing};
 evidence.stage='modal focus withholds background graph-history shortcuts';await open();await page.focus('button[aria-label="close graph commands"]');await page.keyboard.down(process.platform==='darwin'?'Meta':'Control');await page.keyboard.press('z');await page.keyboard.up(process.platform==='darwin'?'Meta':'Control');assert(await page.$eval('.command-menu',e=>e.open));await page.keyboard.press('Escape');assert.deepEqual((await save()).graph,created.graph);assert.deepEqual((await save()).ui,created.ui);
 await execute('Undo draft edit');unchanged(baseline,await save());await execute('Redo draft edit');assert.deepEqual((await save()).graph,created.graph);assert.deepEqual((await save()).ui,created.ui);await execute('Undo draft edit');
 evidence.stage='Arrow keys choose a real inspector result';await open();await search('Inspect conv');await page.keyboard.press('ArrowDown');const selected=await page.$eval('.command-results button[aria-pressed="true"]',e=>e.getAttribute('aria-label').slice('run command inspect:'.length));await page.keyboard.press('Enter');await page.waitForFunction(id=>document.querySelector('input[aria-label="node id"]').value===id,{},selected);assert.equal(selected,'conv_2');unchanged(baseline,await save());await open();await search('conv_1');await page.screenshot({path:path.join(output,'native-command-menu.png'),fullPage:true,captureBeyondViewport:false});await page.keyboard.press('Escape');
 evidence.stage='scoped module creation, interfaces/layout preservation and root navigation';await page.select('select[aria-label="open project"]','example:residual_cnn');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='residual_cnn');await fill('input[aria-label="project id"]','SYNTHETIC_commands');const moduleSource=await save();if(!(await page.$eval('.graph-outline',e=>e.open)))await page.click('.graph-outline summary');await page.click('[aria-label="module outline res1"]');await page.waitForSelector('[aria-label="breadcrumb"]');await execute('Inspect conv_a');await page.waitForFunction(()=>document.querySelector('input[aria-label="node id"]').value==='conv_a');await execute('diag.probe@');const moduleCreated=await save();assert.deepEqual(moduleCreated.graph.nodes,moduleSource.graph.nodes);assert.deepEqual(moduleCreated.graph.edges,moduleSource.graph.edges);const d=moduleCreated.graph.modules.find(d=>d.id==='residual_block'),old=moduleSource.graph.modules.find(m=>m.id===d.id);assert.equal(d.nodes.at(-1).id,'probe_1');assert.deepEqual(d.edges,old.edges);assert.deepEqual(d.inputs,old.inputs);assert.deepEqual(d.outputs,old.outputs);assert.deepEqual(Object.fromEntries(Object.entries(moduleCreated.ui.positions).filter(([key])=>key!=='residual_block@1.0.0/probe_1')),moduleSource.ui.positions);evidence.module={baseline:moduleSource,saved:moduleCreated,native:await validate(moduleCreated.graph)};assert(!evidence.module.native.ok);await execute('Back to project root');assert(!(await page.$('[aria-label="breadcrumb"]')));await execute('Undo draft edit');unchanged(moduleSource,await save());
 evidence.stage='native agent/RL scope exposes existing workspaces but no generic node/create commands';evidence.scopes=[];
 for(const [example,title] of [['rl_cartpole_dqn','RL lab'],['serving_agent','Agent']]){
  await page.select('select[aria-label="open project"]','example:'+example);await page.waitForFunction(id=>document.querySelector('input[aria-label="project id"]').value===id,{},example);await open();await search('Inspect');assert.equal(await page.$$eval('.command-results button',bs=>bs.length),0);await search('Add');assert.equal(await page.$$eval('.command-results button',bs=>bs.length),0);await search('Open '+title);assert.equal(await page.$$eval('.command-results button',bs=>bs.length),1);await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.querySelector('.command-menu').open);evidence.scopes.push({example,title});
 }
 evidence.stage='orphan comment/layout reservation and valid constructor ID';
 const prototype={graph:{schemaVersion:'1.0.0',graphKind:'model',backend:'pytorch',nodes:[{id:'constructor',type:'core.tensor_input',version:'1.0.0',config:{shape:['N',4],dtype:'float32'}}],edges:[]},ui:{schemaVersion:'1.0.0',synthetic:true,description:'SYNTHETIC authored orphan metadata and native constructor input; no training claim',positions:{probe_1:{x:500,y:600}},nodeComments:{}}};
 const prototypeNative=await validate(prototype.graph);assert(prototypeNative.ok);prototype.ui.nodeComments.probe_1={text:'SYNTHETIC retained orphan declaration',author:'SYNTHETIC declared author',authoredAt:new Date().toISOString(),source:{nodeId:'constructor',nodeType:'core.tensor_input',nodeVersion:'1.0.0',kind:'graph',hash:prototypeNative.graphHash}};
 await page.evaluate(async data=>{const r=await fetch('/api/projects/SYNTHETIC_commands',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error('Store labelled prototype '+r.status);},prototype);
 await page.select('select[aria-label="open project"]','project:SYNTHETIC_commands');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='SYNTHETIC_commands'&&document.querySelector('button[aria-label="undo draft edit"]').disabled);const prototypeSaved=await save();await execute('Inspect constructor');await execute('diag.probe@');const reserved=await save();assert(reserved.graph.nodes.some(n=>n.id==='probe_2'));assert(!reserved.graph.nodes.some(n=>n.id==='probe_1'));assert.deepEqual(reserved.ui.nodeComments,prototypeSaved.ui.nodeComments);assert.deepEqual(reserved.ui.positions.probe_1,prototypeSaved.ui.positions.probe_1);assert(Number.isFinite(reserved.ui.positions.probe_2.x));assert.deepEqual(reserved.graph.edges,[]);evidence.orphan={baseline:prototypeSaved,saved:reserved,native:await validate(reserved.graph)};assert(!evidence.orphan.native.ok);await execute('Undo draft edit');unchanged(prototypeSaved,await save());
 assert.deepEqual(evidence.runtimeErrors,[]);assert.deepEqual(evidence.apiErrors,[]);assert.deepEqual(evidence.consoleWarnings,[]);evidence.browserVersion=await browser.version();evidence.status='passed';console.log('PASS actual command menu → native focus/search/pages → keyboard inspection/navigation → disconnected native defaults/missing input → exact Undo/Redo → module scope → agent/RL limitations');
}catch(error){evidence.error=String(error);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true,captureBeyondViewport:false}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync(path.join(output,'evidence.json'),JSON.stringify(evidence,null,2));await browser.close();}
