// Real owned Chrome, real saved drafts and API validation. No invented graph evidence.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {default:puppeteer}=await import(pathToFileURL(process.env.VOID_SMOKE_PUPPETEER).href);
const output=process.env.VOID_SMOKE_OUTPUT;
const evidence={status:'failed',fixture:'SYNTHETIC native module-definition clipboard',runtimeErrors:[],apiErrors:[],consoleWarnings:[]};
const browser=await puppeteer.launch({executablePath:process.env.VOID_SMOKE_CHROME,headless:true,
  args:process.platform==='linux'?['--no-sandbox']:[],defaultViewport:{width:1600,height:1100}});
process.once('SIGTERM',()=>void browser.close());process.once('SIGINT',()=>void browser.close());
const page=await browser.newPage();page.setDefaultTimeout(45000);
page.on('pageerror',e=>evidence.runtimeErrors.push(e.message));
page.on('dialog',d=>d.accept());
page.on('console',m=>{if(['warning','error'].includes(m.type()))evidence.consoleWarnings.push({type:m.type(),text:m.text()});});
page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/')&&r.status()>=400)evidence.apiErrors.push({status:r.status(),url:r.url()});});
const fill=async(selector,value)=>{
  const el=await page.waitForSelector(selector);
  await el.evaluate((el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
  await el.press('Tab');
};
const click=async(label)=>{
  await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(b=>b.textContent.trim()===t&&!b.disabled),{},label);
  for(const h of await page.$$('button'))if(await h.evaluate((e,t)=>e.textContent.trim()===t&&!e.disabled,label))return h.click();
};
const disabled=selector=>page.$eval(selector,e=>e.disabled);
const save=async()=>{
  const pending=page.waitForResponse(r=>r.request().method()==='PUT'&&new URL(r.url()).pathname==='/api/projects/SYNTHETIC_module_clipboard');
  for(const h of await page.$$('.topbar button'))if(await h.evaluate(e=>e.textContent.startsWith('Save'))){await h.click();break;}
  const response=await pending;assert.equal(response.status(),200);
  return page.evaluate(async()=>{const r=await fetch('/api/projects/SYNTHETIC_module_clipboard');if(!r.ok)throw Error('Read saved draft '+r.status);return r.json();});
};
const shortcut=async(redo=false)=>{
  await page.evaluate(()=>document.activeElement?.blur());
  await page.keyboard.down(process.platform==='darwin'?'Meta':'Control');
  if(redo)await page.keyboard.down('Shift');
  await page.keyboard.press('z');
  if(redo)await page.keyboard.up('Shift');
  await page.keyboard.up(process.platform==='darwin'?'Meta':'Control');
};
const get=()=>page.evaluate(async()=>(await fetch('/api/projects/SYNTHETIC_module_clipboard')).json());
const load=async data=>{
 await page.evaluate(async data=>{const r=await fetch('/api/projects/SYNTHETIC_module_clipboard',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error('Stored fixture '+r.status);},data);
 await page.waitForSelector('select[aria-label="open project"] option[value="project:SYNTHETIC_module_clipboard"]');await page.select('select[aria-label="open project"]','project:SYNTHETIC_module_clipboard');await page.waitForFunction(()=>document.querySelector('.toast[role="status"]')?.textContent.includes("Loaded project 'SYNTHETIC_module_clipboard'"));await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='SYNTHETIC_module_clipboard'&&document.querySelector('button[aria-label="undo draft edit"]').disabled);
 for(const button of await page.$$('button[role="tab"]'))if(await button.evaluate(b=>b.textContent.trim()==='Graph')){await button.focus();await button.press('Enter');break;}
};
const openModule=async()=>{if(!(await page.$eval('.graph-outline',e=>e.open)))await page.click('.graph-outline summary');const b=await page.waitForSelector('[aria-label="module outline res1"]');await b.focus();await b.press('Enter');await page.waitForSelector('[aria-label="breadcrumb"]');if(!(await page.$eval('.clipboard-tools',e=>e.open)))await page.click('.clipboard-tools summary');};
const native=graph=>page.evaluate(async graph=>(await fetch('/api/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph})})).json(),graph);
const moduleNative=graph=>page.evaluate(async graph=>(await fetch('/api/modules/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph,moduleId:'residual_block',version:'1.0.0'})})).json(),graph);
const prefix='residual_block@1.0.0/';
try{
 await page.goto(process.env.VOID_SMOKE_URL);await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='reference_cnn');await page.waitForSelector('select[aria-label="open project"] option[value="example:residual_cnn"]');await page.select('select[aria-label="open project"]','example:residual_cnn');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='residual_cnn');await fill('input[aria-label="project id"]','SYNTHETIC_module_clipboard');const original=await save();
 const source={graph:original.graph,ui:{...original.ui,positions:{...original.ui.positions,[prefix+'conv_a']:{x:100,y:200},[prefix+'relu_a']:{x:600,y:300},[prefix+'conv_a_copy']:{x:4,y:8}},nodeComments:{[prefix+'conv_a']:{text:'SYNTHETIC original source note'},[prefix+'conv_a_copy_2']:{text:'SYNTHETIC orphan note'}},unknown:{label:'SYNTHETIC preserved metadata'}}};await load(source);const baseline=await save();assert.deepEqual(baseline.graph,source.graph);assert.deepEqual(baseline.ui,source.ui);evidence.baseline=baseline;const report=await moduleNative(baseline.graph);assert(report.ok);await openModule();
 evidence.stage='real module source identity and excluded boundary cards';assert.equal(await page.$('input[aria-label="copy node __in:x"]'),null);assert.equal(await page.$('input[aria-label="copy node __out:y"]'),null);await click('Clear copy selection');await page.click('input[aria-label="copy node conv_a"]');await page.click('input[aria-label="copy node relu_a"]');await click('Copy selected nodes');await page.waitForFunction(hash=>document.querySelector('.clipboard-provenance')?.textContent.includes(hash),{},report.moduleHash);assert((await page.$eval('.clipboard-provenance',e=>e.textContent)).includes('native module identity'));assert((await page.$eval('.clipboard-provenance',e=>e.textContent)).includes('2 boundary wires omitted'));assert.deepEqual((await save()).ui,baseline.ui);assert(await disabled('button[aria-label="undo draft edit"]'));
 evidence.stage='module append preserves interfaces/old wires/root/unknown UI and orphan keys';await click('Paste copied nodes');const pasted=await save();const before=baseline.graph.modules[0],after=pasted.graph.modules[0];assert.deepEqual(pasted.graph.nodes,baseline.graph.nodes);assert.deepEqual(pasted.graph.edges,baseline.graph.edges);assert.deepEqual({...after,nodes:null,edges:null},{...before,nodes:null,edges:null});assert.deepEqual(after.nodes.slice(0,before.nodes.length),before.nodes);assert.deepEqual(after.edges.slice(0,before.edges.length),before.edges);assert.deepEqual(after.nodes.slice(before.nodes.length).map(n=>n.id),['conv_a_copy_3','relu_a_copy']);assert.deepEqual(after.edges.at(-1).from,{node:'conv_a_copy_3',port:'output'});assert.deepEqual(after.edges.at(-1).to,{node:'relu_a_copy',port:'input'});assert(!after.edges.some(e=>e.from.node==='$in'&&e.to.node==='conv_a_copy_3'));assert.deepEqual(pasted.ui.positions[prefix+'conv_a_copy_3'],{x:180,y:280});assert.deepEqual(pasted.ui.positions[prefix+'relu_a_copy'],{x:680,y:380});assert.deepEqual({...pasted.ui,positions:null},{...baseline.ui,positions:null});for(const [key,value]of Object.entries(baseline.ui.positions))assert.deepEqual(pasted.ui.positions[key],value);assert.notEqual(pasted.graphHash,baseline.graphHash);
 const missing=await native(pasted.graph),moduleMissing=await moduleNative(pasted.graph);assert(!missing.ok&&!moduleMissing.ok);assert(missing.diagnostics.some(d=>d.code==='E_MISSING_INPUT'&&d.nodeId.includes('conv_a_copy_3')));assert(moduleMissing.diagnostics.some(d=>d.code==='E_MISSING_INPUT'));evidence.pasted={saved:pasted,native:missing,moduleNative:moduleMissing};await page.screenshot({path:path.join(output,'module-clipboard.png'),fullPage:true});
 evidence.stage='one exact Undo/Redo and repeated paste with new identities';await click('Undo');const undone=await save();assert.deepEqual(undone.graph,baseline.graph);assert.deepEqual(undone.ui,baseline.ui);assert(await disabled('button[aria-label="undo draft edit"]'));await click('Redo');assert.deepEqual((await save()).graph,pasted.graph);assert.deepEqual((await save()).ui,pasted.ui);await openModule();await click('Paste copied nodes');const repeated=await save();assert.deepEqual(repeated.graph.modules[0].nodes.slice(-2).map(n=>n.id),['conv_a_copy_4','relu_a_copy_2']);assert.deepEqual(repeated.ui.positions[prefix+'conv_a_copy_4'],{x:260,y:360});assert.equal(new Set(repeated.graph.modules[0].edges.map(e=>e.id)).size,repeated.graph.modules[0].edges.length);await click('Undo');assert.deepEqual((await save()).graph,pasted.graph);assert.deepEqual((await save()).ui,pasted.ui);evidence.repeated={saved:repeated,native:await native(repeated.graph)};
 evidence.stage='module-to-root snapshot transfer leaves all module definitions unchanged';if(!(await page.$eval('.clipboard-tools',e=>e.open)))await page.click('.clipboard-tools summary');await click('Paste copied nodes');const root=await save();assert.deepEqual(root.graph.modules,pasted.graph.modules);assert.deepEqual(root.graph.nodes.slice(0,pasted.graph.nodes.length),pasted.graph.nodes);assert.deepEqual(root.graph.edges.slice(0,pasted.graph.edges.length),pasted.graph.edges);assert.deepEqual(root.graph.nodes.slice(-2).map(n=>n.id),['conv_a_copy','relu_a_copy']);assert.deepEqual(root.ui.nodeComments,baseline.ui.nodeComments);assert.deepEqual(root.ui.positions.conv_a_copy,{x:340,y:440});evidence.root={saved:root,native:await native(root.graph)};await click('Undo');assert.deepEqual((await save()).graph,pasted.graph);assert.deepEqual((await save()).ui,pasted.ui);
 evidence.stage='root-to-module transfer keeps target interface and original module body';await click('Clear graph clipboard');await click('Clear copy selection');await page.click('input[aria-label="copy node stem_act"]');await click('Copy selected nodes');await page.waitForFunction(()=>document.querySelector('.clipboard-provenance')?.textContent.includes('native graph identity'));await openModule();await click('Paste copied nodes');const into=await save();assert.equal(into.graph.modules[0].nodes.at(-1).id,'stem_act_copy');assert.deepEqual(into.graph.nodes,pasted.graph.nodes);assert.deepEqual(into.graph.modules[0].inputs,pasted.graph.modules[0].inputs);assert.deepEqual(into.graph.modules[0].outputs,pasted.graph.modules[0].outputs);assert.deepEqual(into.graph.modules[0].edges,pasted.graph.modules[0].edges);evidence.into={saved:into,native:await native(into.graph)};await click('Undo');assert.deepEqual((await save()).graph,pasted.graph);assert.deepEqual((await save()).ui,pasted.ui);
 evidence.stage='actual native constructor module node with topology fallback';const renamedGraph={...baseline.graph,modules:baseline.graph.modules.map(d=>d.id==='residual_block'?{...d,nodes:d.nodes.map(n=>n.id==='conv_a'?{...n,id:'constructor'}:n),edges:d.edges.map(e=>({...e,from:{...e.from,node:e.from.node==='conv_a'?'constructor':e.from.node},to:{...e.to,node:e.to.node==='conv_a'?'constructor':e.to.node}}))}:d)};await load({graph:renamedGraph,ui:baseline.ui});const constructorBefore=await save(),constructorReport=await moduleNative(constructorBefore.graph);assert(constructorReport.ok);await openModule();await click('Clear copy selection');await page.click('input[aria-label="copy node constructor"]');await click('Copy selected nodes');await page.waitForFunction(hash=>document.querySelector('.clipboard-provenance')?.textContent.includes(hash),{},constructorReport.moduleHash);await click('Paste copied nodes');const constructorAfter=await save();assert.deepEqual(constructorAfter.ui.positions[prefix+'constructor_copy'],{x:370,y:120});assert.deepEqual(constructorAfter.graph.modules[0].inputs,constructorBefore.graph.modules[0].inputs);assert.deepEqual(constructorAfter.graph.modules[0].outputs,constructorBefore.graph.modules[0].outputs);evidence.constructor={saved:constructorAfter,native:await native(constructorAfter.graph),moduleNative:await moduleNative(constructorAfter.graph)};assert(!evidence.constructor.native.ok);await click('Undo');assert.deepEqual((await save()).graph,constructorBefore.graph);assert.deepEqual((await save()).ui,constructorBefore.ui);
 evidence.stage='incompatible kind refuses without edit';await click('New tabular graph');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='untitled_tabular');if(!(await page.$eval('.clipboard-tools',e=>e.open)))await page.click('.clipboard-tools summary');assert(await page.$$eval('.clipboard-provenance button',bs=>bs.find(b=>b.textContent==='Paste copied nodes').disabled));assert(await disabled('button[aria-label="undo draft edit"]'));
 assert.deepEqual(evidence.runtimeErrors,[]);assert.deepEqual(evidence.apiErrors,[]);assert.deepEqual(evidence.consoleWarnings,[]);evidence.browserVersion=await browser.version();evidence.status='passed';console.log('PASS module clipboard → actual native source identity → interfaces/orphan keys preserved → omitted boundaries/native errors → one Undo/Redo → repeat/cross-scope transfer → kind refusal');
}catch(error){evidence.error=String(error);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync(path.join(output,'evidence.json'),JSON.stringify(evidence,null,2));await browser.close();}
