// Real owned Chrome, real saved drafts and API validation. No invented graph evidence.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {default:puppeteer}=await import(pathToFileURL(process.env.VOID_SMOKE_PUPPETEER).href);
const output=process.env.VOID_SMOKE_OUTPUT;
const evidence={status:'failed',fixture:'SYNTHETIC native RL outline',runtimeErrors:[],apiErrors:[],consoleWarnings:[]};
const browser=await puppeteer.launch({executablePath:process.env.VOID_SMOKE_CHROME,headless:true,
  args:process.platform==='linux'?['--no-sandbox']:[],defaultViewport:{width:1600,height:1100}});
process.once('SIGTERM',()=>void browser.close());process.once('SIGINT',()=>void browser.close());
const page=await browser.newPage();page.setDefaultTimeout(45000);
page.on('pageerror',e=>evidence.runtimeErrors.push(e.message));
page.on('dialog',d=>d.accept());
page.on('console',m=>{if(['warning','error'].includes(m.type()))evidence.consoleWarnings.push({type:m.type(),text:m.text()});});
page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/')&&r.status()>=400)evidence.apiErrors.push({status:r.status(),url:r.url()});});
const fill=async(selector,value)=>{
  const el=await page.waitForSelector(selector);
  await el.evaluate((el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
  await el.press('Tab');
};
const click=async(label)=>{
  await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(b=>b.textContent.trim()===t&&!b.disabled),{},label);
  for(const h of await page.$$('button'))if(await h.evaluate((e,t)=>e.textContent.trim()===t&&!e.disabled,label))return h.click();
};
const disabled=selector=>page.$eval(selector,e=>e.disabled);
const save=async()=>{
  const pending=page.waitForResponse(r=>r.request().method()==='PUT'&&new URL(r.url()).pathname==='/api/projects/SYNTHETIC_rl_outline');
  for(const h of await page.$$('.topbar button'))if(await h.evaluate(e=>e.textContent.startsWith('Save'))){await h.click();break;}
  const response=await pending;assert.equal(response.status(),200);
  return page.evaluate(async()=>{const r=await fetch('/api/projects/SYNTHETIC_rl_outline');if(!r.ok)throw Error('Read saved draft '+r.status);return r.json();});
};

const native=graph=>page.evaluate(async graph=>(await fetch('/api/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph})})).json(),graph);
const tab=async name=>{for(const h of await page.$$('.rlworkspace [role="tab"]'))if(await h.evaluate((e,t)=>e.textContent.trim()===t,name)){await h.click();return;}throw Error('Missing RL tab '+name);};
const structure=()=>tab('Structure');
const load=async data=>{await page.evaluate(async data=>{const r=await fetch('/api/projects/SYNTHETIC_rl_outline',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error('Stored RL fixture '+r.status);},data);await page.select('select[aria-label="open project"]','project:SYNTHETIC_rl_outline');await page.waitForFunction(()=>document.querySelector('.toast[role="status"]')?.textContent.includes("Loaded project 'SYNTHETIC_rl_outline'"));await structure();};
const ready=hash=>page.waitForFunction(hash=>document.querySelector('.rl-outline .provenance')?.textContent.includes(hash),{},hash);
const ids=()=>page.$$eval('.rl-outline tbody tr',rows=>rows.map(r=>r.querySelector('button[aria-label^="inspect rl outline "]').getAttribute('aria-label').slice('inspect rl outline '.length)));
const inspect=async id=>{const b=await page.waitForSelector(`[aria-label="inspect rl outline ${id}"]`);await b.focus();await b.press('Enter');await page.waitForFunction(id=>document.querySelector('[aria-label="RL node inspector"] h4')?.textContent==='RL node inspector · '+id&&document.activeElement===document.querySelector('[aria-label="RL node inspector"] h4'),{},id);};
const contracts=async(id,report)=>{await inspect(id);for(const [key,label]of [['inputShapes','rl native input contracts'],['outputShapes','rl native output contracts']]){const raw=await page.$eval(`[aria-label="${label}"]`,e=>e.textContent);if(report.nodes[id][key]===undefined)assert.equal(raw,'not returned');else assert.deepEqual(JSON.parse(raw),report.nodes[id][key]);}};
try{
 await page.goto(process.env.VOID_SMOKE_URL);await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='reference_cnn'&&document.querySelectorAll('.react-flow__node').length===10);await page.waitForSelector('select[aria-label="open project"] option[value="example:rl_cartpole_dqn"]');await page.select('select[aria-label="open project"]','example:rl_cartpole_dqn');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='rl_cartpole_dqn');await fill('input[aria-label="project id"]','SYNTHETIC_rl_outline');const initial=await save();
 await load({graph:initial.graph,ui:{...initial.ui,synthetic:true,description:'SYNTHETIC declared RL structure; actual native contracts, no trained policy or return claim',unknown:{preserved:true}}});const baseline=await save(),report=await native(baseline.graph);assert(report.ok);await ready(report.graphHash);evidence.baseline={saved:baseline,native:report};
 evidence.stage='native spaces,reward,network,equation and keyboard exact inspector without edits';assert.deepEqual(await ids(),baseline.graph.nodes.map(n=>n.id));for(const id of await ids())await contracts(id,report);await contracts('qnet',report);assert.equal(report.nodes.qnet.params,report.rl.network.params);assert.deepEqual(report.nodes.qnet.outputShapes.network.shapes,report.rl.network.shapes);await page.screenshot({path:path.join(output,'native-rl-outline.png'),fullPage:true});
 await fill('input[aria-label="rl outline search"]','observationSpace');const expected=baseline.graph.nodes.filter(n=>JSON.stringify(report.nodes[n.id].inputShapes).includes('observationSpace')||JSON.stringify(report.nodes[n.id].outputShapes).includes('observationSpace')).map(n=>n.id);assert.deepEqual(await ids(),expected);await fill('input[aria-label="rl outline search"]','');await contracts('env',report);await click('Open Environment controls for env');await page.waitForFunction(()=>document.querySelector('select[aria-label="environment id"]')?.value==='CartPole-v1');assert.equal(await page.$eval('select[aria-label="environment id"]',e=>e.value),'CartPole-v1');await structure();await contracts('learner',report);await click('Open Learner controls for learner');await page.waitForSelector('[aria-label="update equation"]');assert((await page.$eval('[aria-label="update equation"]',e=>e.textContent)).includes(report.rl.learner.equation.targetEquation));await structure();let after=await save();assert.deepEqual(after.graph,baseline.graph);assert.deepEqual(after.ui,baseline.ui);assert(await disabled('button[aria-label="undo draft edit"]'));
 evidence.stage='real native missing-input errors/filter no invented equation';const bad={...baseline.graph,edges:baseline.graph.edges.filter(e=>e.id!=='e4')};await load({graph:bad,ui:baseline.ui});const invalid=await save(),badReport=await native(invalid.graph);assert(!badReport.ok);await ready(badReport.graphHash);await page.click('input[aria-label="rl outline native errors only"]');const errorIds=bad.nodes.filter(n=>badReport.diagnostics.some(d=>d.nodeId===n.id&&d.severity==='error')).map(n=>n.id);assert.deepEqual(await ids(),errorIds);assert(errorIds.includes('learner'));await contracts('learner',badReport);for(const d of badReport.diagnostics.filter(d=>d.nodeId==='learner'))assert((await page.$eval('.rl-outline',e=>e.textContent)).includes(d.code));assert.deepEqual((await save()).graph,invalid.graph);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.invalid={saved:invalid,native:badReport};await page.click('input[aria-label="rl outline native errors only"]');
 evidence.stage='real pending validation suppresses prior contracts, valid constructor node';const rename=id=>id==='env'?'constructor':id;const graph={...baseline.graph,nodes:baseline.graph.nodes.map(n=>({...n,id:rename(n.id)})),edges:baseline.graph.edges.map(e=>({...e,from:{...e.from,node:rename(e.from.node)},to:{...e.to,node:rename(e.to.node)}}))};
 let reached;const seen=new Promise(resolve=>{reached=resolve;}),held=[];await page.setRequestInterception(true);const gate=request=>{const data=request.postData();if(new URL(request.url()).pathname==='/api/validate'&&request.method()==='POST'&&data&&JSON.parse(data).graph.nodes.some(n=>n.id==='constructor')){held.push(request);reached();}else void request.continue();};page.on('request',gate);await load({graph,ui:baseline.ui});await seen;await page.waitForFunction(()=>document.querySelector('.rl-outline .provenance')?.textContent.includes('Native RL validation pending'));await inspect('constructor');assert.equal(await page.$$eval('[aria-label="rl native input contracts"],[aria-label="rl native output contracts"]',es=>es.length),0);assert.equal((await page.$eval('.rl-outline',e=>e.textContent)).includes('E_MISSING_INPUT'),false);evidence.pending={realRequestsHeld:held.length,visible:await page.$eval('.rl-outline .provenance',e=>e.textContent)};for(const request of held)await request.continue();page.off('request',gate);await page.setRequestInterception(false);const constructor=await save(),constructorReport=await native(constructor.graph);assert(constructorReport.ok);await ready(constructorReport.graphHash);await contracts('constructor',constructorReport);assert.deepEqual((await save()).ui,constructor.ui);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.constructor={saved:constructor,native:constructorReport};
 evidence.stage='actual GridWorld contract replaces CartPole spaces';await page.select('select[aria-label="open project"]','example:rl_gridworld_builder');await page.waitForFunction(()=>document.querySelector('input[aria-label="project id"]').value==='rl_gridworld_builder');await fill('input[aria-label="project id"]','SYNTHETIC_rl_outline');const grid=await save();await structure();const gridReport=await native(grid.graph);assert(gridReport.ok);await ready(gridReport.graphHash);await contracts('env',gridReport);assert.deepEqual(gridReport.rl.environment.observationSpace.shape,[30]);assert.equal(gridReport.rl.environment.actionSpace.n,4);await contracts('qnet',gridReport);assert.equal((await page.$eval('.rl-outline .provenance',e=>e.textContent)).includes(report.graphHash),false);assert.deepEqual((await save()).graph,grid.graph);assert.deepEqual((await save()).ui,grid.ui);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.grid={saved:grid,native:gridReport};
 evidence.stage='75native rows/50+25pages with real duplicate-family global refusal';const nodes=[...graph.nodes,...Array.from({length:69},(_,i)=>({id:'extra_'+String(i).padStart(3,'0'),type:'rl.reward',version:'1.0.0',config:{components:[]}}))],pagesGraph={...graph,nodes};await load({graph:pagesGraph,ui:{schemaVersion:'1.0.0',positions:{},synthetic:true,description:'SYNTHETIC75declared nodes for paging; intentionally repeated reward family causes native E_RL_NODE_COUNT, no policy/quality/performance claim'}});const pages=await save(),pagesReport=await native(pages.graph);assert(!pagesReport.ok);assert(pagesReport.diagnostics.some(d=>d.code==='E_RL_NODE_COUNT'));await ready(pagesReport.graphHash);const first=await ids();assert.equal(first.length,50);await click('Next RL outline nodes');const second=await ids();assert.equal(second.length,25);await click('Previous RL outline nodes');assert.deepEqual(await ids(),first);await click('Next RL outline nodes');await fill('input[aria-label="rl outline search"]','extra_068');assert.deepEqual(await ids(),['extra_068']);assert(await page.$$eval('.rl-outline button',bs=>bs.find(b=>b.textContent==='Previous RL outline nodes').disabled));await contracts('extra_068',pagesReport);assert.equal(await page.$$eval('[aria-label="RL node inspector"] button',bs=>bs.filter(b=>b.textContent.includes('Open Environment')).length),0);assert.deepEqual((await save()).graph,pages.graph);assert.deepEqual((await save()).ui,pages.ui);assert(await disabled('button[aria-label="undo draft edit"]'));evidence.pages={saved:pages,native:pagesReport,first,second};
 assert.deepEqual(evidence.runtimeErrors,[]);assert.deepEqual(evidence.apiErrors,[]);assert.deepEqual(evidence.consoleWarnings,[]);evidence.browserVersion=await browser.version();evidence.status='passed';console.log('PASS native RL outline → exact contracts/keyboard inspector → native errors/pending guard →constructor/grid spaces →75native rows/global refusal/paging → no edits/history');
}catch(error){evidence.error=String(error);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync(path.join(output,'evidence.json'),JSON.stringify(evidence,null,2));await browser.close();}
