"""Display names and one-line purposes for the registry listing (the library). Facts only."""
from __future__ import annotations

META: dict[str, tuple[str, str, str]] = {
    # type: (display name, category, purpose)
    "core.tensor_input": ("Tensor input", "Core", "Entry point of the graph: a tensor of the declared shape and dtype (N is the batch size)."),
    "pytorch.nn.conv2d": ("Conv2D", "Layers", "Slides learned filters over the input and sums over input channels: one feature map per filter."),
    "pytorch.nn.relu": ("ReLU", "Layers", "Elementwise max(0, x)."),
    "pytorch.nn.max_pool2d": ("MaxPool2D", "Layers", "Keeps the maximum of each window; shrinks the spatial size."),
    "pytorch.nn.adaptive_avg_pool2d": ("AdaptiveAvgPool2D", "Layers", "Averages each channel down to a fixed output size (1x1 = global average pooling)."),
    "pytorch.nn.flatten": ("Flatten", "Layers", "Merges dimensions into one, keeping the batch axis."),
    "pytorch.nn.linear": ("Linear", "Layers", "Fully connected layer: y = xW^T + b."),
    "pytorch.loss.cross_entropy": ("CrossEntropy", "Loss", "Classification loss on logits and integer class targets."),
    "core.sub": ("Subtract", "Tensor ops", "Elementwise a - b (equal shapes)."),
    "core.add": ("Add", "Tensor ops", "Elementwise a + b (equal shapes)."),
    "core.square": ("Square", "Tensor ops", "Elementwise x^2."),
    "core.sum": ("Sum", "Tensor ops", "Sum over chosen dims."),
    "core.mean": ("Mean", "Tensor ops", "Mean over chosen dims with an explicit divisor rule."),
    "core.scalar_mul": ("Scalar multiply", "Tensor ops", "Multiply every element by a constant."),
    # ---- tabular graph kind
    "tabular.csv_source": ("CSV table source", "Data", "Reads a local CSV file into a table; the file's SHA-256 is recorded with every run."),
    "tabular.profile": ("Table profile", "Data", "Types, missing counts, duplicates, summary statistics and suspect columns of the input table (exact, all rows)."),
    "tabular.duplicates": ("Duplicate policy", "Data", "Group rows by a fixed identity rule and keep first / last / none, or only report. Run before splitting."),
    "tabular.select_columns": ("Typed column selection", "Data", "Choose columns and declare each column's type; conversion failures are reported."),
    "tabular.drop_missing": ("Drop missing rows", "Data", "Remove rows with missing values in chosen columns (a fixed rule, nothing fitted)."),
    "tabular.train_validation_split": ("Train / validation split", "Partition", "Seeded, recorded partition; optional stratification or grouping."),
    "tabular.fit_standardize": ("Fit standardization", "Preprocessing", "Learns mean and standard deviation from the TRAINING partition. Produces a fitted state, not a table."),
    "tabular.fit_onehot": ("Fit one-hot encoding", "Preprocessing", "Learns the categories from the TRAINING partition. Produces a fitted state."),
    "tabular.fit_impute": ("Fit imputation", "Preprocessing", "Learns mean / median (or a constant) from the TRAINING partition for missing values."),
    "tabular.apply_transform": ("Apply fitted transform", "Preprocessing", "Applies a fitted state to a table of any partition without refitting."),
    "sklearn.linear_regression": ("Linear regression (OLS)", "Models", "Ordinary least squares (scikit-learn LinearRegression). No learning rate or epochs."),
    "sklearn.logistic_regression": ("Logistic regression", "Models", "L2-regularized logistic regression (scikit-learn, lbfgs)."),
    "sklearn.metrics": ("Validation metrics", "Evaluation", "MSE / RMSE / MAE / R2 or accuracy / log-loss / ROC-AUC / confusion matrix on the connected table."),
    "tabular.predictions_export": ("Predictions export", "Evaluation", "Observed, predicted (and residual or class probabilities) per row id, stored as a CSV artifact."),
    "scipy.gamma_function": ("Gamma function", "Statistics", "Gamma(x), the special function (not a probability distribution)."),
    "scipy.gamma_distribution": ("Gamma distribution", "Statistics", "Gamma probability distribution with explicit shape, scale or rate, and location."),
    "scipy.tail_probability": ("Tail probability", "Statistics", "P(T >= t) or P(T <= t) under a reference distribution, via the survival function."),
    "scipy.hypothesis_test": ("Hypothesis test", "Statistics", "Null, alternative, statistic, p-value, alpha, decision and assumptions for a tail-probability test."),
    "scipy.two_group_comparison": ("Two-group comparison", "Statistics", "Welch / Student / paired t-test or Mann-Whitney U, with effect size, interval, design and diagnostics."),
    # ---- connected data (Milestone 2b)
    "postgres.query": ("PostgreSQL query", "Connected data", "Visual query builder (compiled to parameterized SQL) or read-only raw SQL on a PostgreSQL connection. Every run records the query, server snapshot token and a content hash."),
    "s3.csv_source": ("S3 CSV object", "Connected data", "Reads a CSV/TSV object from an S3-compatible bucket. Pinned by object version id when the bucket is versioned; otherwise flagged as limited reproducibility."),
    "s3.object_listing": ("S3 object listing", "Connected data", "Object metadata under a prefix (key, size, ETag, modified, optional id extracted from the key). Bodies are not read."),
    "dvc.csv_source": ("DVC dataset", "Connected data", "Reads a DVC-tracked CSV at a Git revision; records the resolved commit, the DVC md5 and the content hash."),
    "tabular.join": ("Join tables", "Data", "Joins two tables in the worker with a key-cardinality and unmatched-record report, row multiplication, and where it executed. NULL keys never match."),
    # ---- Milestone 3: tensor primitives, diagnostics, structure
    "tensor.constant": ("Constant", "Tensor ops", "A typed literal (scalar or nested list) with a dtype. Not a parameter."),
    "tensor.arange": ("Arange", "Tensor ops", "Integer positions 0..n-1 (int64), e.g. for positional embeddings."),
    "tensor.add": ("Add (broadcast)", "Tensor ops", "a + b with PyTorch broadcasting (declared in the explain panel); equal dtypes required."),
    "tensor.sub": ("Subtract (broadcast)", "Tensor ops", "a - b with broadcasting."),
    "tensor.mul": ("Multiply (broadcast)", "Tensor ops", "Elementwise a * b with broadcasting."),
    "tensor.div": ("Divide (broadcast)", "Tensor ops", "Elementwise a / b with broadcasting (floats). Dividing by 0 gives inf/NaN: clamp the denominator when that can happen."),
    "tensor.matmul": ("Matmul", "Tensor ops", "Batched matrix product [..., m, k] @ [..., k, n]."),
    "tensor.reshape": ("Reshape", "Tensor ops", "Same elements, new axes; N stays the leading batch axis; optional axis names."),
    "tensor.permute": ("Permute axes", "Tensor ops", "Reorder axes; optional names for the output axes."),
    "tensor.concat": ("Concatenate", "Tensor ops", "Join two tensors along an axis."),
    "tensor.slice": ("Slice", "Tensor ops", "Python-style start:end:step along one axis."),
    "tensor.exp": ("Exp", "Tensor ops", "e^x."),
    "tensor.log": ("Log", "Tensor ops", "Natural logarithm."),
    "tensor.sqrt": ("Sqrt", "Tensor ops", "Square root."),
    "tensor.abs": ("Abs", "Tensor ops", "Absolute value."),
    "tensor.neg": ("Negate", "Tensor ops", "-x."),
    "tensor.tanh": ("Tanh", "Tensor ops", "Hyperbolic tangent."),
    "tensor.sigmoid": ("Sigmoid", "Tensor ops", "1 / (1 + e^-x)."),
    "tensor.gelu": ("GELU", "Tensor ops", "Gaussian error linear unit (exact)."),
    "tensor.clamp": ("Clamp", "Tensor ops", "Limit values to [min, max]; gradient is 0 where clamped."),
    "tensor.softmax": ("Softmax", "Tensor ops", "Numerically stable softmax along one axis."),
    "tensor.log_softmax": ("Log-softmax", "Tensor ops", "Fused stable log-softmax along one axis."),
    "tensor.where": ("Where / mask", "Tensor ops", "Pick a where cond is true, else b (broadcast)."),
    "tensor.compare": ("Compare", "Tensor ops", "Elementwise >, >=, <, <=, ==, != producing a bool tensor."),
    "tensor.logical": ("Logical and/or/xor", "Tensor ops", "Elementwise boolean logic."),
    "tensor.logical_not": ("Logical not", "Tensor ops", "Elementwise boolean negation."),
    "tensor.any_all": ("Any / all", "Tensor ops", "Reduce a bool tensor to one scalar bool (a predicate for a select block)."),
    "tensor.cast": ("Cast dtype", "Tensor ops", "Explicit dtype conversion."),
    "tensor.layernorm": ("LayerNorm", "Layers", "Normalise over the last k axes per item; learned scale and shift."),
    "tensor.batchnorm": ("BatchNorm", "Layers", "Per-channel batch normalisation with explicit train/eval behaviour and running statistics (buffers)."),
    "tensor.dropout": ("Dropout", "Layers", "Randomly zeroes elements in train mode; train/eval behaviour is explicit."),
    "tensor.embedding": ("Embedding", "Layers", "Lookup of learned vectors by integer id."),
    "tensor.dense": ("Dense (last axis)", "Layers", "Linear map applied to the last axis of a tensor of any rank >= 2."),
    "diag.probe": ("Probe", "Diagnostics", "Observation-only: records statistics of the value passing through while a capture covers it."),
    "diag.histogram": ("Histogram", "Diagnostics", "Observation-only: records a histogram of the value passing through while a capture covers it."),
    "diag.timer": ("Timer", "Diagnostics", "Observation-only: records when execution reaches this point while a capture covers it."),
    "diag.assert": ("Assert", "Diagnostics", "EXECUTION-CHANGING: stops the run with a localized failure when a check on the value fails."),
    "core.composite": ("Module instance", "Modules", "One instance of a reusable module (subgraph with a typed signature). Clones parameters unless it shares with another instance."),
    "core.repeat": ("Repeat", "Modules", "Applies a module a fixed number of times with loop-carried state; parameters tied across iterations by default."),
    "core.select": ("Select (branches)", "Modules", "Two module branches with identical signatures; a scalar bool predicate picks the outputs. Both branches are evaluated."),
    "code.block": ("Python code block", "Code", "Optional Python implementation with a typed interface; runs in an isolated subprocess with limits."),
    # ---- agent graph kind (Milestone 4)
    "agent.set_state": ("Set state", "State", "Writes state fields from literals, copies, templates, counters or lengths. The field's reducer decides how a write combines with the old value."),
    "agent.prompt": ("Prompt / messages", "Prompts", "Ordered message templates plus memory selections, retrieved chunks and tool results; every character range links to its source."),
    "agent.chat_model": ("Chat model", "Models", "Model invocation (not training): provider, model, temperature, max tokens, seed where supported, timeout. Records the exact request and provider-reported usage."),
    "agent.structured_output": ("Structured output", "Models", "Asks for a JSON object matching a visually declared schema, validates it, retries per the retry policy and routes on failure."),
    "agent.embed_text": ("Embed text", "Retrieval", "Embeds one text field; records the embedding identity, dimension and norm."),
    "agent.retrieve": ("Retriever", "Retrieval", "Top-k similarity search over a persisted index with a score threshold; scores and the cut-off chunks are recorded."),
    "agent.citations": ("Citation check", "Retrieval", "Checks [chunk_id] markers in generated text against the chunks actually retrieved; invalid markers are flagged, never invented."),
    "agent.tool_call": ("Tool", "Tools", "Calls a tool with declared effects and bounded capabilities. External effects require an approval interrupt and run once."),
    "agent.human_interrupt": ("Human input", "Control", "Pauses the thread with a pending-input form (approve / reject / edit); resumes from the checkpoint."),
    "agent.memory_select": ("Memory selection", "Memory", "Applies a visual memory policy (retrieve, filter, rank, deduplicate, token budget, summarize) and records every record's decision."),
    "agent.memory_write": ("Memory write", "Memory", "Writes to the thread's conversation or the long-term store with validation, scope, evidence and an audit entry; optionally behind an accept/reject stage."),
    # ---- rl graph kind (Milestone 5)
    "rl.reward": ("Reward components", "Reinforcement learning", "Per-component weights and switches on top of the environment's separate raw reward components."),
    "rl.environment": ("Environment", "Reinforcement learning", "A tested Gymnasium environment: id and version, time limit, wrappers, seed and autoreset mode; spaces are shown typed."),
    "rl.q_network": ("Q-network", "Reinforcement learning", "A model graph mapping an observation to one Q-value per discrete action (the same lowering as every model graph)."),
    "rl.replay_buffer": ("Replay buffer", "Reinforcement learning", "Uniform replay with a global transition id, episode, step, policy version and the true next observation for every transition."),
    "rl.dqn_learner": ("DQN learner", "Reinforcement learning", "Target-network DQN: y = r + gamma (1 - terminated) max Q_target(s', a'); Huber or squared TD loss; epsilon-greedy collection."),
    "rl.evaluation": ("Evaluation", "Reinforcement learning", "Greedy episodes on separate environment instances with declared seeds; return, length, termination vs truncation, success."),
    # ---- unsupervised nodes (tabular graph kind, Milestone 5)
    "sklearn.kmeans": ("K-means", "Unsupervised", "Lloyd / k-means++ clustering with inertia, per-cluster objective contributions and assignment distances."),
    "sklearn.gaussian_mixture": ("Gaussian mixture", "Unsupervised", "Soft clustering by EM; log-likelihood, BIC / AIC, responsibilities."),
    "sklearn.dbscan": ("DBSCAN", "Unsupervised", "Density-based clustering with core / border / noise status; noise is not a cluster."),
    "sklearn.pca": ("PCA", "Unsupervised", "Principal components of the centered features: explained variance, loadings, reconstruction error."),
    "sklearn.projection": ("2-D projection (non-metric)", "Unsupervised", "t-SNE embedding for viewing only; distances and cluster separation in it are not evidence."),
    "sklearn.cluster_diagnostics": ("Cluster diagnostics", "Unsupervised", "Method-appropriate internal metrics, elbow, seed / bootstrap stability, and external metrics only when labels are declared."),
}
