"""Display names and one-line purposes for the registry listing (the library). Facts only."""
from __future__ import annotations

META: dict[str, tuple[str, str, str]] = {
    # type: (display name, category, purpose)
    "core.tensor_input": ("Tensor input", "Core", "Entry point of the graph: a tensor of the declared shape and dtype (N is the batch size)."),
    "pytorch.nn.conv2d": ("Conv2D", "Layers", "Slides learned filters over the input and sums over input channels: one feature map per filter."),
    "pytorch.nn.relu": ("ReLU", "Layers", "Elementwise max(0, x)."),
    "pytorch.nn.max_pool2d": ("MaxPool2D", "Layers", "Keeps the maximum of each window; shrinks the spatial size."),
    "pytorch.nn.adaptive_avg_pool2d": ("AdaptiveAvgPool2D", "Layers", "Averages each channel down to a fixed output size (1x1 = global average pooling)."),
    "pytorch.nn.flatten": ("Flatten", "Layers", "Merges dimensions into one, keeping the batch axis."),
    "pytorch.nn.linear": ("Linear", "Layers", "Fully connected layer: y = xW^T + b."),
    "pytorch.loss.cross_entropy": ("CrossEntropy", "Loss", "Classification loss on logits and integer class targets."),
    "core.sub": ("Subtract", "Tensor ops", "Elementwise a - b (equal shapes)."),
    "core.add": ("Add", "Tensor ops", "Elementwise a + b (equal shapes)."),
    "core.square": ("Square", "Tensor ops", "Elementwise x^2."),
    "core.sum": ("Sum", "Tensor ops", "Sum over chosen dims."),
    "core.mean": ("Mean", "Tensor ops", "Mean over chosen dims with an explicit divisor rule."),
    "core.scalar_mul": ("Scalar multiply", "Tensor ops", "Multiply every element by a constant."),
    # ---- tabular graph kind
    "tabular.csv_source": ("CSV table source", "Data", "Reads a local CSV file into a table; the file's SHA-256 is recorded with every run."),
    "tabular.profile": ("Table profile", "Data", "Types, missing counts, duplicates, summary statistics and suspect columns of the input table (exact, all rows)."),
    "tabular.duplicates": ("Duplicate policy", "Data", "Group rows by a fixed identity rule and keep first / last / none, or only report. Run before splitting."),
    "tabular.select_columns": ("Typed column selection", "Data", "Choose columns and declare each column's type; conversion failures are reported."),
    "tabular.drop_missing": ("Drop missing rows", "Data", "Remove rows with missing values in chosen columns (a fixed rule, nothing fitted)."),
    "tabular.train_validation_split": ("Train / validation split", "Partition", "Seeded, recorded partition; optional stratification or grouping."),
    "tabular.fit_standardize": ("Fit standardization", "Preprocessing", "Learns mean and standard deviation from the TRAINING partition. Produces a fitted state, not a table."),
    "tabular.fit_onehot": ("Fit one-hot encoding", "Preprocessing", "Learns the categories from the TRAINING partition. Produces a fitted state."),
    "tabular.fit_impute": ("Fit imputation", "Preprocessing", "Learns mean / median (or a constant) from the TRAINING partition for missing values."),
    "tabular.apply_transform": ("Apply fitted transform", "Preprocessing", "Applies a fitted state to a table of any partition without refitting."),
    "sklearn.linear_regression": ("Linear regression (OLS)", "Models", "Ordinary least squares (scikit-learn LinearRegression). No learning rate or epochs."),
    "sklearn.logistic_regression": ("Logistic regression", "Models", "L2-regularized logistic regression (scikit-learn, lbfgs)."),
    "sklearn.metrics": ("Validation metrics", "Evaluation", "MSE / RMSE / MAE / R2 or accuracy / log-loss / ROC-AUC / confusion matrix on the connected table."),
    "tabular.predictions_export": ("Predictions export", "Evaluation", "Observed, predicted (and residual or class probabilities) per row id, stored as a CSV artifact."),
    "scipy.gamma_function": ("Gamma function", "Statistics", "Gamma(x), the special function (not a probability distribution)."),
    "scipy.gamma_distribution": ("Gamma distribution", "Statistics", "Gamma probability distribution with explicit shape, scale or rate, and location."),
    "scipy.tail_probability": ("Tail probability", "Statistics", "P(T >= t) or P(T <= t) under a reference distribution, via the survival function."),
    "scipy.hypothesis_test": ("Hypothesis test", "Statistics", "Null, alternative, statistic, p-value, alpha, decision and assumptions for a tail-probability test."),
    "scipy.two_group_comparison": ("Two-group comparison", "Statistics", "Welch / Student / paired t-test or Mann-Whitney U, with effect size, interval, design and diagnostics."),
    # ---- connected data (Milestone 2b)
    "postgres.query": ("PostgreSQL query", "Connected data", "Visual query builder (compiled to parameterized SQL) or read-only raw SQL on a PostgreSQL connection. Every run records the query, server snapshot token and a content hash."),
    "s3.csv_source": ("S3 CSV object", "Connected data", "Reads a CSV/TSV object from an S3-compatible bucket. Pinned by object version id when the bucket is versioned; otherwise flagged as limited reproducibility."),
    "s3.object_listing": ("S3 object listing", "Connected data", "Object metadata under a prefix (key, size, ETag, modified, optional id extracted from the key). Bodies are not read."),
    "dvc.csv_source": ("DVC dataset", "Connected data", "Reads a DVC-tracked CSV at a Git revision; records the resolved commit, the DVC md5 and the content hash."),
    "tabular.join": ("Join tables", "Data", "Joins two tables in the worker with a key-cardinality and unmatched-record report, row multiplication, and where it executed. NULL keys never match."),
}
