import { useState } from "react";
import { api, errorText } from "../api";
import { usePolling } from "../hooks";
import type { Graph, UiDoc } from "../types";
interface Overview { remote: any[]; exports: any[]; runs: { id: string; status: string; shareableMetricsArtifacts: { sha256: string; node: string }[] }[]; trackerRuntimeAvailable: boolean; sdkExamples: string[]; capabilities: unknown }
function Record({ value }: { value: unknown }) { return <pre className="prod-recorded">{JSON.stringify(value, null, 2)}</pre>; }
function EvidenceResult({ value }: { value: any }) {
  const rows = value.runs.flatMap((r: any) => r.summaries.filter((s: any) => s.type === "sklearn.metrics").flatMap((s: any) => Object.entries(s.summary.values ?? {}).map(([key, measured]) => ({ run: r.runId, node: s.node, key, measured, sha: s.sha256, partition: s.summary.evaluatedPartition }))));
  return <><table><thead><tr><th>Run / node</th><th>Metric</th><th>Observed value</th><th>Partition / evidence</th></tr></thead><tbody>{rows.map((r: any) => <tr key={`${r.run}:${r.node}:${r.key}`}><th scope="row">{r.run} / {r.node}</th><td>{r.key}</td><td>{String(r.measured)}</td><td>{r.partition} · {r.sha.slice(0, 12)}</td></tr>)}</tbody></table><details><summary>Source, preprocessing and full evidence</summary><Record value={value} /></details></>;
}
export function ScaleWorkspace({ graph, ui, projectId, onImport, onOpenRun }: { graph: Graph; ui: UiDoc; projectId: string; onImport: (p: any) => void; onOpenRun: (id: string) => void }) {
  const overview = usePolling<Overview>("/api/integrations", 3000); const data = overview.data;
  const [tab, setTab] = useState("Workers"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<unknown>(null);
  const [endpoint, setEndpoint] = useState("http://127.0.0.1:8778"); const [tokenEnv, setToken] = useState("VOID_WORKER_TOKEN");
  const [runId, setRun] = useState(""); const [adapter, setAdapter] = useState("mlflow"); const [destination, setDestination] = useState("void-local"); const [metrics, setMetrics] = useState(false); const [artifacts, setArtifacts] = useState<string[]>([]);
  const [include, setInclude] = useState(false); const [bundle, setBundle] = useState(""); const [importId, setImportId] = useState("imported_project"); const [example, setExample] = useState("offset");
  const [a, setA] = useState(""); const [b, setB] = useState(""); const [conclusion, setConclusion] = useState("");
  const acceptance = usePolling<{ rows: { id: string; scenario: string; status: string; scope: string; evidence: string[] }[] }>(tab === "Acceptance" ? "/api/acceptance" : null, 60000);
  const act = async (fn: () => Promise<unknown>) => { setBusy(true); setError(""); try { setResult(await fn()); overview.reload(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const runs = data?.runs ?? []; const selected = runs.find((r) => r.id === runId);
  return <div className="fullws production"><header className="prod-heading"><h2>Scale and integrations</h2><p>Separate local CPU worker, local MLflow, W&B offline and inert project packages. Values come from recorded runs.</p></header>
    <nav className="tabs" aria-label="integration views">{["Workers", "Trackers", "Packages", "Extensions", "Evidence", "Acceptance"].map((t) => <button key={t} aria-pressed={tab === t} onClick={() => { setTab(t); setResult(null); }}>{t}</button>)}</nav>
    {(error || overview.error) && <p role="alert">{error || overview.error}</p>}
    {tab === "Workers" && <section className="prod-panel"><h3>Authenticated loopback worker</h3><p>Explicitly transfer the current native tabular CSV/JSONL graph and immutable input bytes (8 MiB maximum). This is another local process; cross-host TLS, GPU and distributed scheduling are unavailable.</p>
      <label>Worker endpoint <input aria-label="worker endpoint" value={endpoint} onChange={(e) => setEndpoint(e.target.value)} /></label><label>Token environment reference <input aria-label="worker token reference" value={tokenEnv} onChange={(e) => setToken(e.target.value)} /></label>
      <button disabled={busy || graph.graphKind !== "tabular"} onClick={() => act(() => api.post("/api/integrations/remote", { graph, endpoint, tokenEnv, projectId }))}>Submit snapshot to worker</button>
      {data?.remote.map((r) => <article key={r.id}><b>{r.status} · {r.id.slice(0, 12)}</b><p>{r.location}</p><button disabled={busy} onClick={() => act(() => api.post(`/api/integrations/remote/${r.id}/refresh`, {}))}>Reconnect and retrieve</button><button disabled={busy || !r.workerRunId || ["completed", "failed", "cancelled"].includes(r.status)} onClick={() => act(() => api.post(`/api/integrations/remote/${r.id}/cancel`, {}))}>Cancel worker job</button>{r.runId && <button onClick={() => onOpenRun(r.runId)}>Inspect retrieved run</button>}<details><summary>Recorded job</summary><Record value={r} /></details></article>)}
    </section>}
    {tab === "Trackers" && <section className="prod-panel"><h3>Explicit sharing and recovery</h3><p>Metadata shares run ID, graph hash and terminal status. Metrics and numeric evaluation summaries require explicit selection. W&B exports stay offline. Confirmed mappings are reused on reconnect.</p>
      <label>Recorded terminal run <select aria-label="tracker run" value={runId} onChange={(e) => { setRun(e.target.value); setArtifacts([]); }}><option value="">choose…</option>{runs.map((r) => <option key={r.id} value={r.id}>{r.id} · {r.status}</option>)}</select></label>
      <label>Adapter <select aria-label="tracker adapter" value={adapter} onChange={(e) => setAdapter(e.target.value)}><option value="mlflow">Native local MLflow</option><option value="wandb">Native W&B offline</option></select></label><label>Experiment / project <input value={destination} onChange={(e) => setDestination(e.target.value)} /></label>
      <label><input type="checkbox" checked={metrics} onChange={(e) => setMetrics(e.target.checked)} /> Share recorded numeric metrics</label>
      {selected?.shareableMetricsArtifacts.map((x) => <label key={x.sha256}><input type="checkbox" checked={artifacts.includes(x.sha256)} onChange={(e) => setArtifacts((prev) => e.target.checked ? [...prev, x.sha256] : prev.filter((v) => v !== x.sha256))} /> Share {x.node} summary {x.sha256.slice(0, 12)}</label>)}
      <button disabled={busy || !selected} onClick={() => act(() => api.post("/api/integrations/exports", { runId, adapter, project: destination, shareMetrics: metrics, artifactSha256: artifacts }))}>Queue selected export</button>
      {!data?.trackerRuntimeAvailable && <p>Native tracker environment is unavailable; queued exports remain pending. See README installation commands.</p>}
      {data?.exports.map((x) => <article key={x.id}><b>{x.adapter} · {x.status} · {x.runId}</b><button disabled={busy || !data.trackerRuntimeAvailable} onClick={() => act(() => api.post(`/api/integrations/exports/${x.id}/sync`, {}))}>Reconnect tracker export</button><details><summary>Sharing and confirmed mapping</summary><Record value={x} /></details></article>)}
    </section>}
    {tab === "Packages" && <section className="prod-panel"><h3>Reusable inert project package</h3><p>Includes graph, settings, UI, dependency identities and declared environment requirements. Import preserves unknown operations and blocks execution when required dependencies differ. It never installs Python or executes the graph.</p>
      <label><input type="checkbox" checked={include} onChange={(e) => setInclude(e.target.checked)} /> Include explicit local CSV/JSONL snapshots (up to 8 MiB)</label>
      <button disabled={busy} onClick={() => act(async () => { const p = await api.post<any>("/api/packages/export", { graph, ui, includeCsv: include }); setBundle(JSON.stringify(p, null, 2)); return { identity: p.identity, requirements: p.requirements }; })}>Export current project package</button>
      <label>Package JSON <textarea aria-label="project package JSON" value={bundle} onChange={(e) => setBundle(e.target.value)} rows={10} /></label><label>Import project ID <input value={importId} onChange={(e) => setImportId(e.target.value)} /></label>
      <button disabled={busy || !bundle} onClick={() => act(() => api.post("/api/packages/inspect", { package: JSON.parse(bundle), projectId: importId }))}>Inspect package dependencies</button>
      <button disabled={busy || !bundle} onClick={() => act(async () => { const p = await api.post<any>("/api/packages/import", { package: JSON.parse(bundle), projectId: importId }); onImport(p); return p; })}>Import and open package</button>
    </section>}
    {tab === "Extensions" && <section className="prod-panel"><h3>Operation SDK conformance</h3><p>The manifest pins native implementation, version, port/settings schemas, state/effects, inspector, documentation, examples and numerical tests. Only explicitly trusted native Python can be activated at startup with VOID_PLUGIN_MANIFESTS. Opening a graph does not activate code.</p><label>Bundled trusted example <select value={example} onChange={(e) => setExample(e.target.value)}>{data?.sdkExamples.map((e) => <option key={e}>{e}</option>)}</select></label><button disabled={busy || !data?.sdkExamples.includes(example)} onClick={() => act(() => api.post("/api/extensions/conformance", { example }))}>Run native conformance checks</button></section>}
    {tab === "Evidence" && <section className="prod-panel"><h3>Compare runs and record a conclusion</h3><p>Compare recorded evaluation summaries, inspect source and preprocessing, and save a conclusion with exact evidence identities before promotion.</p>{[["Baseline", a, setA], ["Variant", b, setB]].map(([label, val, setter]) => <label key={String(label)}>{String(label)} <select aria-label={`${String(label).toLowerCase()} evidence run`} value={val as string} onChange={(e) => (setter as (s: string) => void)(e.target.value)}><option value="">choose…</option>{runs.map((r) => <option key={r.id}>{r.id}</option>)}</select></label>)}
      <button disabled={busy || !a || !b} onClick={() => act(() => api.post("/api/evidence/compare", { runIds: [a, b] }))}>Compare recorded evidence</button>
      <button disabled={!a} onClick={() => onOpenRun(a)}>Inspect baseline intermediates</button><button disabled={!b} onClick={() => onOpenRun(b)}>Inspect variant intermediates</button>
      <label>Conclusion <textarea aria-label="evidence conclusion" value={conclusion} onChange={(e) => setConclusion(e.target.value)} /></label><button disabled={busy || !a || !b || !conclusion.trim()} onClick={() => act(() => api.post("/api/evidence", { runIds: [a, b], conclusion }))}>Record conclusion with evidence</button>
    </section>}
    {tab === "Acceptance" && <section className="prod-panel"><h3>A01–A64 acceptance checklist</h3><p>Bounded evidence does not claim every part of the product vision. Unsupported scenarios and precise limits remain explicit.</p>{acceptance.error && <p role="alert">{acceptance.error}</p>}<table><thead><tr><th>Scenario</th><th>Status</th><th>Scope and evidence</th></tr></thead><tbody>{acceptance.data?.rows.map((r) => <tr key={r.id}><th scope="row">{r.id} · {r.scenario}</th><td>{r.status}</td><td>{r.scope}<details><summary>Verification references</summary>{r.evidence.map((p) => <div key={p}><code>{p}</code></div>)}</details></td></tr>)}</tbody></table></section>}
    {result != null && <section className="prod-panel" aria-label="integration result"><h3>Recorded result</h3>{Array.isArray((result as any).runs) ? <EvidenceResult value={result} /> : <Record value={result} />}</section>}
  </div>;
}
